name: storage

on:
  push
#  pull_request:
#    paths:
#    - 'FirebaseStorage**'

jobs:
  core:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with: # Set the secret as an input
        super_secret: ${{ secrets.TestSecret2 }}
    - name: Hello world action
      # env: # Or as an environment variable
      #   super_secret: ${{ secrets.SuperSecret }}
      run: |
        echo "abc"
        echo ${{ secrets.TestSecret2 }}
        echo "xyz"
        #cp ${{ secrets.TestSecret }} foo
        #cat foo


    # - uses: actions/checkout@v1
    # - name: Set up
    #   run: |
    #     bundle install
    #     bundle exec pod --version
    # - name: FirebaseCore
    #   run: ./scripts/pod_lib_lint.rb FirebaseCore.podspec --platforms=ios
