name: storage

on:
  push
#  pull_request:
#    paths:
#    - 'FirebaseStorage**'

jobs:
  core:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
         secret_file: ${{ secrets.TestSecret }}
    - name: Hello world action
      env:
         myString: ${{ 'Mona the Octocat' }}
         #foo: {{ 'my value' }}
         GITHUB_CONTEXT: ${{ toJson(github) }}
         super_secret: ${{ secrets.TestSecret2 }}
      run: |
        echo "abc"
        echo "$myString"
        echo $HOME
        cp "$secret_file" paul-foo
        cat paul-foo
        echo "xyz"
        
        
  # cp ${{ secrets.TestSecret }} foo
  #cat foo

    # - uses: actions/checkout@v1
    # - name: Set up
    #   run: |
    #     bundle install
    #     bundle exec pod --version
    # - name: FirebaseCore
    #   run: ./scripts/pod_lib_lint.rb FirebaseCore.podspec --platforms=ios
